### ISSUE TITLE
Hook to fetch parameter names for stored procedures

### ISSUE THREAD

**Issue by chilversc** [StackExchange/dapper-dot-net#393] opened 2015-11-12 10:31 UTC
In MS SQL Server specifying parameters that do not exist in stored procedure results in "Procedure or function <name> has too many arguments specified."

This makes using standard model objects with a stored procedure quite fragile.

```csharp
db.Execute(sql: "dbo.SomeProc", commandType: CommandType.StoredProcedure, param: someObject);
```

In this example, if you added an extra property to `someObject` then the query would break. This forces having first have to copy the object to an anonymous object, which is awkward if the object has many properties.

While using `EXEC` could avoid this, that then means having to repeat a list of all the parameters which could be many and is redundant as this could be fetched from the server.

Having Dapper fetch the parameter list as standard is outside Dapper's scope. However, Dapper already has support for parameter sniffing in standard text queries and only adds those parameters to the command. Dapper could support supplying a custom delegate to fetch parameter that is used when the command type is `StoredProcedure`.

It would be up to the delegate to handle the database specific method of fetching parameters and any caching of those parameters.

Returning null from the parameter provider indicates that the parameter information is not available and the parameters should be derived as normal from the param object.

```csharp
delegate List<string> StoredProcedureParameterProvider(IDbConnection connection, string storedProcedureName)

SqlMapper.StoredProcedureParameterProvider = (connection, storedProcedureName) =>
    // full implementation would want to cache this based upon the name
    connection.Query<string> (
        @"SELECT PARAMETER_NAME
            FROM INFORMATION_SCHEMA.PARAMETERS
            WHERE SPECIFIC_SCHEMA = PARSENAME(@storedProcedureName, 2)
            AND SPECIFIC_NAME = PARSENAME(@storedProcedureName, 1)",
        buffered: false,
        param: {storedProcedureName})
        .Select(name => name.TrimStart('@')
        .ToList ();
```

**Comment by mgravell** [comment] 2015-11-19 00:35
I can't help thinking that the more obvious thing here is ... just supply the right parameters:

    param: new { someObject.Id, someObject.Name }

??

**Comment by chilversc** [comment] 2015-11-19 09:32
I just find that awkward when I have a stored procedure that takes 20 parameters, and my object has say 21,  so I need all but 1 property.

I wanted to get something similar to the existing parameter sniffing but without having to also write out `EXEC Foo @a = @a, @b = @b, @c = @c, ...`. It's just redundant information since the DB already has this information.

One other option I suppose would be to query the DB for the parameters, then use reflection on the object for its properties and generate the EXEC statement.

**Comment by mgravell** [comment] 2015-11-19 15:02
The "query the DB for the parameters" approach is doubly-problematic:

- it introduces roundtrips
 - either per call, or cached, but then you have issues with people changing the definition underneath you
- it relies on database-specific metadata APIs

There may, however, be a way to do this using a provider, but the problem is that you'd end up moving all the "when used for *this* proc, it needs these 3, but when used for *that* proc it needs these 20" **further** away from the object.

There is another way of doing it:

    Execute("EXEC myProc @Foo, @Bar, @Blap, ...", Model);

Just a thought. Not sure if you think that is better or worse.

**Comment by NickCraver** [comment] 2015-11-27 14:38
I'm also in this "this isn't a problem Dapper should solve" boat - this just adds a ton of complexity and inefficiency for what should be a "update code that calls a stored procedure when it changes". There are many RDBMS security roadblocks, etc. that prevent this from working as well. 

The only way I could see this working at all is in an on-exception-then-check scenario, but that has metadata security assumptions that break with many platforms as well. It'd also require a per-provider implementation to maintain which would be quite a large addition and maintenance cost.

**Comment by chilversc** [comment] 2015-11-30 10:41
I wasn't thinking that dapper should provide any implementation, just a hook in the method where it sniffs the parameters from the SQL query so that if the command type is `StoredProcedure` then the hook is called to fetch a list of parameter names. In a similar way that there is a hook for custom types.

I could use the `EXEC` method, it just introduces one more thing to remember to update and redundant declarations. Now I have to add the parameter to the procedure, add a property to the object then remember to update the call to the stored procedure.

So I'd end up with

```csharp
Execute(@"EXECUTE dbo.FooProc
    @ID = @ID,
    @X = @X,
    @Y = @Y,
    ...
   @Z = @Z", model);
```

Though I'm not sure what those extra `@name = ...` does to the parameter sniffing.

**Comment by mgravell** [comment] 2015-11-30 12:26
If all dapper knows is the stored procedure name, it can't do *automated*
sniffing without the issues already discussed. If you used an API hook to
map stored procedure names to parameters, then sure: that could *work*, but
that is no different to the bit where you say:

> "I could use the EXEC method, it just introduces one more thing to
remember to update and redundant declarations"

This is *exactly* as many more things and redundancy, but it is at least
local and visible to the call; the code shown that uses EXECUTE would
already work correctly and only send the required members.

**Comment by NickCraver** [comment] 2016-01-04 12:55
Closing this out as a feature not really desirable for Dapper core.

**Closed by NickCraver** 2016-01-04 12:55 UTC
