### ISSUE TITLE
Value cannot be null when calling First on the result of connection.Query<T>

### ISSUE THREAD

**Issue by thomasek** [StackExchange/dapper-dot-net#388] opened 2015-11-10 15:10 UTC
Under some circumstances, the following query:

``` C#
connection.Query<T>("SELECT..", {}, null, true, 600, null);
```

returns null. 
Since we are calling `.First()` on the result of this query, this call is resulting in the following exception:

``` Log
System.Exception: Exception: Value cannot be null.
Parameter name: source   at System.Linq.Enumerable.First[TSource](IEnumerable1 source)
```

If I run the query against the DB, it will return result, however in this case Dapper does not seem to be sending the query to the SQL server (I don't see anything in the profiler). So the inpur parameter seems to be correct.

**Comment by NickCraver** [comment] 2015-11-11 02:36
Hmm, that shouldn't happen - you should get an empty `List<T>` back.

What are you passing into the param field? It's unclear from the example. 

Side note: unless you're on a very old version of C# - you need not pass all the parameters, only what you're using, for example: 
```C#
connection.Query<T>("SELECT...", myParams, commandTimeout: 600);
```

**Comment by thomasek** [comment] 2015-11-11 06:14
it is following:
DateTime date = DateTime.Now;
"SELECT * from mytable where date = @date", new {date }, 120;
it is an object of type datetime.
I have also forgotten to say that I have my debugger attached while doing this test.

**Comment by thomasek** [comment] 2015-11-11 06:15
I have also tried an option without an anonymous type (defining a class with one property of type datetime), but no difference. Other queries used in the exactly same manner are returning results.

**Comment by mgravell** [comment] 2015-11-11 09:30
Can I ask what RDBMS this is? I seem to recall there was a bug in one of the ADO.NET providers that gave something similar to this (maybe it was an `NullReferenceException`)

**Comment by mgravell** [comment] 2015-11-11 09:38
Can I also check that you're running against a current version of dapper? The `Query<T>` method never returns `null`; it either returns a raw iterator block (`yield return`, etc), or a `List<T>` created by calling `ToList()` on the same iterator block. A complete runable example would be awesome (again, with the dapper version number and the name of the RDBMS).

As a side-note, if `mytable.date` is a `datetime`, I would expect this to return zero rows; I wonder if the problem is actually something more akin to downstream processing. Hard to say without the extra context.

**Comment by NickCraver** [comment] 2015-11-27 13:16
@thomasek any update on the above questions? There's also a new `.QueryFirstOrDefault<T>()` that @mgravell added you'll want to check out now :)

**Comment by NickCraver** [comment] 2017-01-28 15:53
Closing out to cleanup

**Closed by NickCraver** 2017-01-28 15:53 UTC
