### ISSUE TITLE
Dapper should call the GetXXXX methods on IDataRecord

### ISSUE THREAD

**Issue by mburbea** [StackExchange/dapper-dot-net#227] opened 2014-12-24 23:53 UTC
Dapper currently always calls the indexer on `IDataRecord` instead of the potentially faster methods of `GetXXXX`. `SqlDataReader` for instance will not actually box if you call `GetInt32` or any of the other primitive types. 
As the deserializer is being built with aid from the target type and the reader we can always inspect the reader and issue the correct command. For the types affect the new logic would look something like (for a type with a field of Uint32 but the reader returns an Int32)

```
if(reader.IsDBNull(0)) { /*jump to null check */}
else{
    local0 = reader.GetInt32(0);
    obj.Field = checked((uint)local0);
}
```

For the types unaffected it should be the same. We should probably not use `GetChar` as that isn't implemented on SqlDataReader. After all, it's already special cased.

**Comment by dimzon** [comment] 2015-01-12 00:48
the problem is - sometimes some providers returns their own types when using GetValue http://docs.oracle.com/html/B14164_01/featSafeType.htm

So your typecasting to "proper" value type can fail. Using concrete GetXXX is much more safe

**Comment by mburbea** [comment] 2015-01-12 03:59
From the documentation it seems only with the appropriate switch, and only
when not read via a data reader or into a dataset. I also don't think this
is a useful feature. I think most code out there deals with decimals and
date times, not the byte arrays or string representations.
On Jan 11, 2015 7:48 PM, "Dmitry" <notifications@github.com> wrote:
>
> the problem is - sometimes some providers returns their own types when
using GetValue http://docs.oracle.com/html/B14164_01/featSafeType.htm
>
> So your typecasting to "proper" value type can fail. Using concrete
GetXXX is much more safe

**Comment by NickCraver** [comment] 2017-01-28 15:58
Since this can't work across providers reliably (e.g. Oracle above), closing this out.

**Closed by NickCraver** 2017-01-28 15:58 UTC
Labels: needs-investigation
