### ISSUE TITLE
Dapper should call Command.Cancel at the end of enumerating for single result set

### ISSUE THREAD

**Issue by mburbea** [StackExchange/dapper-dot-net#228] opened 2014-12-26 16:23 UTC
Currently dapper will call `IDataReader.NextResult` forcing the command to continue internally reading all the data until it reaches the end. 

This generally isn't a huge problem (most of the times you do call `Query` on a row with one record set), but if you are calling a store procedure with multiple result sets but you only care about the first one, you'll suffer a bit of a performance hit. I can submit a PR replacing the calls to `while(reader.NextResult()){ }` with `cmd.Cancel()` unless there is a good reason as to why Dapper is doing this.

**Comment by NickCraver** [comment] 2015-10-11 16:42
Closing this out since as Marc explains, it's the intended behavior.

**Closed by NickCraver** 2015-10-11 16:42 UTC
