### ISSUE TITLE
Could not load file or assembly 'Dapper, Version=1.50.0.0, Culture=neutral, PublicKeyToken=null', when referencing dapper by dynamically compiled PCL.

### ISSUE THREAD

**Issue by B-Esmaili** [StackExchange/dapper-dot-net#425] opened 2015-12-20 07:13 UTC
In my application i scan all plugins (as PCL) from a directory and compile theme with rozlyn.but when for each dependency of that PCL i call `Assembly.Load` it throws the exception `Could not load file or assembly 'Dapper, Version=1.50.0.0, Culture=neutral, PublicKeyToken=null'` , it worth mention that the mentioned plugin has references for other libraries such as `Autofac` which loads without any problem, and plugin compiles successfully (without Dapper) , but when i call `Assembly.Load` with fully qualified path of Dapper dll file it again compiles successfully.I am really excited about the fact that why this only happens for dapper? any suggestions?

**Comment by mgravell** [comment] 2015-12-20 09:45
Dapper doesn't do anything crazy re files / loading. I have no clue why if
would be doing something different here. Do you have a minimal repro that
shows the problem (and ideally: shows it working for some other "hello
world" dll)?

**Comment by mgravell** [comment] 2015-12-20 09:46
The line "Version=15000" is odd, though

**Comment by B-Esmaili** [comment] 2015-12-20 10:37
Thanks for you'r response marc  I am trying to prepare such a report.But some extra thing happened is , i published the application and strangely enough i have all packages in `packages` folder except 'Dapper' whereas i haven't added some rule for excluding `Dapper` from publish.

**Comment by B-Esmaili** [comment] 2015-12-20 10:56
I think i found the problem , i haven't referenced plugins from the application directly , rather i  compile theme at run-time and it seems Visual Studio takes care of things when we define a strict reference between two project and loads package from appropriate locations .but something misleading was the fact that other libraries was loading correctly and this was happening because i have reference for theme in main framework library.now i have to search after an approach to tel VS load dependencies from my plugins as well.
again thanks for you'r time.

**Comment by NickCraver** [comment] 2017-01-28 15:51
Closing out to cleanup

**Closed by NickCraver** 2017-01-28 15:51 UTC

**Comment by sureshTajeesh** [comment] 2021-12-01 16:12
I found the root cause of the issue . The reason for the issue is Dapper nuget package needs to be refer while accessing the application either in Dot net core web api or mvc application. So that the application can able to load the appropriate assembly in place.
![image](https://user-images.githubusercontent.com/24358631/144270715-78a62b86-d26d-44be-884a-8dfdac4fca1e.png)

**Comment by mgravell** [comment] 2021-12-01 20:01
Weird. Normally transitive dependencies would be resolved automatically. This suggests that you have two library dependencies that each take a secondary dependency on Dapper, and they're squabbling over the version. In that case, adding the top level ref would act as a casting vote, and would typically also emit binding redirects as needed. Without knowing your project structure, this can only be conjecture, of course.
